apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app
  labels:
    app: flask-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: emekaezedozie276/flask-app:v0.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: app_env
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi


# Why this matters:
# replicas: 2 — always have 2 pods running for resilience
# livenessProbe — restarts unhealthy pods
# readinessProbe — removes unhealthy pods from service traffic
# resources.requests — K8s scheduler knows minimum needs
# resources.limits — prevents pod from hogging cluster resources